version: "3"
services:
  postgres-db:
    image: postgres
    container_name: erp_db
    env_file:
      - erp/.env
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: ${ERP_PG_DATABASE}
      POSTGRES_USER: ${ERP_PG_USER}
      POSTGRES_PASSWORD: ${ERP_PG_PASSWORD}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - paytonkawa-network

  erp-app:
    build:
      context: ./erp
      dockerfile: Dockerfile
    container_name: erp-app
    env_file:
      - erp/.env
    ports:
      - 8888:8000
    depends_on:
      - postgres-db
    networks:
      - paytonkawa-network



  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8890:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  paytonkawa-network:
    external: true
