version: "3"
services:
  postgres-db:
    image: postgres
    container_name: crm_db
    env_file:
      - crm/.env
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: ${CRM_PG_DATABASE}
      POSTGRES_USER: ${CRM_PG_USER}
      POSTGRES_PASSWORD: ${CRM_PG_PASSWORD}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
