  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8890:8080"
      - "50000:50000"
    volumes:
      - ${pwd}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
